### ISSUE TITLE
data-scroll element jumps on first inview appearance

### ISSUE THREAD

**Issue by moritzlang** [locomotivemtl/locomotive-scroll#104]
Hello,

I want to animate an element with "data-scroll-speed" property. But when the element first appears in the view it makes a small jump to the top. I tried different approaches on the css but could not find a solution.

[Codepen](https://codepen.io/mlang/pen/NWqBymV)

**To Reproduce**
1. Open the codepen
2. Scroll down
3. See the element on the bottom jumping a bit to the top

**Expected behavior**
The element should not jump upwards.

**Screenshots**
[Video](https://streamable.com/hzzgs)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 80

**Comment by knynkwl** [comment]
+1 Running into this issue as well.

**Comment by jarovision** [comment]
try setting a target with `data-scroll-target` and choose a parent which is a bit larger than your element :)

**Comment by moritzlang** [comment]
@jarovision Unfortunately this did not work for me.

But I found a solution, which works for my use case: Because the jump happens on the first inview appearance I set the global in-view trigger `offset` to `-100%`. For elements that need the inview offset I set the element attribute `data-scroll-offset` to the desired value, which overrides the global offset.

**Comment by JonQuayle** [comment]
Just noticed today that I am getting the same sort of behaviour for a series of elements but also not all elements on a page. Have double checked the CSS and that is bullet proof as it was working a few days ago. In fact, the entire library seems buggy across the board - has the most recent update affected something?

**Comment by Psycoleg** [comment]
a little tricky solution for this issue:
`[data-scroll]{
  opacity: 0;
}`

**Comment by Psycoleg** [comment]
a little tricky solution for this issue on css (add fadein to hide jump):
```
[data-scroll]{
  opacity: 0;
  transition: opacity .1s linear;
}
[data-scroll].is-inview{
  opacity: 1;
}

**Comment by JonQuayle** [comment]
Thanks, I can see how that works. I've done more testing and this is only occurring in Safari. It's almost like a glitch though - text contained in the div that is showing the issue flickers visible to not visible when scrolling through the page. The weird thing is that I have other elements exactly like this in other pages of the site that are behaving normally. It is literally only this page and has started since the last update a couple of days ago. Have tried everything but the more I persist with this plugin the more issues keep cropping up, kinda feeling like its not worth the effort anymore. Even the inspector doesn't show any anomalies :/.

**Comment by quentinhocde** [comment]
Hello guys, 

Sorry for the delay, it will be fixed in the next release with this commit https://github.com/locomotivemtl/locomotive-scroll/commit/85e59405f0fd52b7ab4c760e0388e5d91313eb3b
Now, every elements with a speed are transformed with their good positions on `init()`

I hope everything will be good :) 

Thanks :)
