### ISSUE TITLE
Hide header on scroll

### ISSUE THREAD

**Issue by fcisio** [locomotivemtl/locomotive-scroll#132]
Hi, I'm trying to adapt [this tutorial](https://medium.com/mtholla/create-a-transitioning-header-using-react-hooks-like-mediums-c70ed211f7c9) with Locomotive Scoll and React.

I've been working on it for a while, and can't seen to figure it out.

Has anyone did something similar or as any pointers?
Thanks

**Comment by dejan-77** [comment]
> Hi, I'm trying to adapt [this tutorial](https://medium.com/mtholla/create-a-transitioning-header-using-react-hooks-like-mediums-c70ed211f7c9) with Locomotive Scoll and React.
> 
> I've been working on it for a while, and can't seen to figure it out.
> 
> Has anyone did something similar or as any pointers?
> Thanks

Hey mate :) 
I had a similar question and here is the answer:

[https://github.com/locomotivemtl/locomotive-scroll/issues/127](url)

Unfortunately it didn’t work for me because I’m not a developer and I don’t know how to make it work. I did everything as written, but still... If you can help me with it, I would be very grateful. 

thank you and cheers
Dejan
