### ISSUE TITLE
Cant find the instace object "smoothMobile"

### ISSUE THREAD

**Issue by GodwinEbikwo** [locomotivemtl/locomotive-scroll#196]
Hello 👋

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

Thank you 👊

**Comment by jaro-io** [comment]
hey there.
i don't know if this is the right answer for you. but since version 4 the values are stored at a new position.

```
scroll.options.isMobile
scroll.options.isTablet
```

hope this helps!
🍡

**Comment by quentinhocde** [comment]
Hello,

Please do not describe your issue just in the title...

There is a context system since v4.0.
The `smoothMobile` option is no longer available. You can check the [readme ](https://github.com/locomotivemtl/locomotive-scroll#instance-options).
Now there is an object mobile and tablet, with some options like `smooth`.

Thank you 🤘
