### ISSUE TITLE
Animation is not working properly in mobile  Responsive 

### ISSUE THREAD

**Issue by khaled4dev** [locomotivemtl/locomotive-scroll#206]
Hello 👋
I created this website using locomotive scroll animation but I tried in mobile responsive that animation not working properly .
https://vernonclinic.netlify.app/

Thank you 👊

**Comment by marcoribeiroweb** [comment]
Hi 👋
I think that's because the animations are _"smooth only"_ and the smooth option is disabled by default on mobile. If you want 
the animation on mobile you have to pass the instance option `tablet` & `smartphone`.
Like this:

```
const scroll = new LocomotiveScroll({
    el: document.querySelector('[data-scroll-container]'),
    smooth: true,
    smartphone: {
        smooth: true
    }
});
```

Be aware that this will disable the Native scroll for mobile devices.
Hope it helps. 👍

**Comment by khaled4dev** [comment]
I added this code but its not working same issue

**Comment by khaled4dev** [comment]
need to edit   smoothMobile:!1;    to     smoothMobile:1;

Thank you its working.

**Comment by Jesuscodejs** [comment]
Thanks. :)
