### ISSUE TITLE
When smooth: true, positon: fixed blocks stop working. REACT

### ISSUE THREAD

**Issue by Th0rd** [locomotivemtl/locomotive-scroll#67]
When I try to turn on smooth, all elements with position fixed become static, but in inspector remain fixed and I'm losing all my parallax effects. 
I just want to use this library for smooth scrolling, nothing more.

**Comment by quentinhocde** [comment]
First of all, Hi.
There is a template for issues, please make sure to use it if you need help.

(psst... It's not possible to use fixed element in a smooth scroll container, because all sections are translated. It's the main thing of a smooth scroll, the document doesn't scroll so all fixed element (wich are relative to the document and the native scroll value) are not fixed.
We need to put them outside the scroll container.)
