### ISSUE TITLE
Locomotive not working on non-desktop resolutions

### ISSUE THREAD

**Issue by mlaborde** [locomotivemtl/locomotive-scroll#74]
Hello everybody!

First of all, just wanted to say locomotive is awesome. It really brings to the table a smooth, animated experience to the browser. There's only one thing: I can't make it work on smaller devices such as tablets or phones.

**Describe the bug**
When you open the page on tablet mode or mobile, it doesn't transform elements.

**To Reproduce**
1 - Open locomotive demo page in Chrome
2 - Open developer tools -> Switch to mobile emulation -> select iPad
3 - Refresh the page

**Expected behavior**
I don't know if there's something blocking the behavior, or is "by definition", but doesn't animate the elements

If there is any workaround for this, it'd be great

Thanks a lot in advance  👊

**Comment by quentinhocde** [comment]
Hey!

Thank you for your support 🙏
The `smoothMobile` is an option, and by default it set to false (in the demo page too). It's not a bug, you can set to `true` if you want!

We decided to set the default value to `false` because it takes a lot of performance and we prioritize simple animations and content-first on mobile for our projects.

Thanks!
