### ISSUE TITLE
Tab navigation and smooth scrolling break… everything

### ISSUE THREAD

**Issue by thomas-dm** [locomotivemtl/locomotive-scroll#83]
Hi there 👋

We’re trying out Locomotive Scroll and we just found out the using the `Tab` key to navigate between links when smooth scrolling is active essentially breaks everything. You get negative scroll offsets, overflown items… It’s kind of a nightmare. 😕

**To Reproduce**
1. Go to pretty much every website that uses Locomotive Scroll. Say, https://bornandbredbrand.com/ , for instance.
2. Hit the `Tab` key.

**Expected behavior**
Bringing focus to a link with the tab key should not cause the transform applied on each sections to be erratic.

**Desktop:**
 - OS: macOS 10.15
 - Browser: Chrome
 - Version: 80.0.3987.100

Thanks!

**Comment by Jerek0** [comment]
Hi and thanks for the feedback! Since 79f4fa11e9d7940a2d64274a4f97dca33b7d61ea, keyboard navigation should be improved 👍

**Comment by jarovision** [comment]
hey @Jerek0 
i am still having a lot of trouble with the tab key. it is breaking mostly all the sites i work on. the problem is that locomotive always tries to scroll to the next focused element when navigating via the tab key, even when this element is outside of the site wrapper.

for example, i have a horizontal slider with form elements. the inactive slides are on `position: absolute` and hidden on the very far right of the page. if you select a visible form element (e.g. a textfield) and then press the tab key, locomotive scrolls horizontally to the next textfield which is hidden and then the next one and next one, moving the site more and more off the screen.

![Kapture 2020-07-06 at 22 20 05](https://user-images.githubusercontent.com/20298313/86639110-b17fb800-bfd8-11ea-93d2-711fcb7c5666.gif)

in the example @thomas-dm mentioned, you can see the same behaviour but vertically with elements positioned off the screen.

would be great if we could just completely turn of the navigation with the tab key in locomotives settings.
🎉

**Comment by jarovision** [comment]
```
$(document).keydown(function(e) {

    var keyCode = e.keyCode || e.which;

    // Enter, Tab, Space
    if (keyCode == 9 || keyCode == 32) {

        e.preventDefault();
        return false;
    }
});
```

little workaround to disable tab and space key completely.

**Comment by robizzt** [comment]
Is there any way to set offset for tab scrolling? Cause if you have fixed navigation, the field would get behind navigation.
