### ISSUE TITLE
The basic example don't visually works properly

### ISSUE THREAD

**Issue by pierredarrieutort** [locomotivemtl/locomotive-scroll#90]
[The basic example ](https://github.com/locomotivemtl/locomotive-scroll#basic-example) not properly visually works until we change the following value in [_locomotive-scroll.css_](https://github.com/locomotivemtl/locomotive-scroll/blob/master/dist/locomotive-scroll.css#L14) :

[Original render:](https://github.com/locomotivemtl/locomotive-scroll/blob/master/dist/locomotive-scroll.css#L14)
`.has-scroll-smooth [data-scroll-container] { min-height: 100vh; }`

Working render :
`.has-scroll-smooth [data-scroll-section] { min-height: 100vh; }`

At this time, when we replicate the basic example the "original line" acting on container is useless, unless we change it to target the section :/

**Comment by antoineboulanger** [comment]
Hey, 
the sections can be less than 100vh so we can't add this property. The container min-height is useful. 

Indeed the basic example doesn't really work because it's too small to scroll, without styles. It's more of a code example than a visual demo. We might add some visual demos in the future. Thanks for your feedback.
