### ISSUE TITLE
1px jiiter on some data-scroll-section's

### ISSUE THREAD

**Issue by tiansial** [locomotivemtl/locomotive-scroll#97]
Hello 👋

**Describe the bug**
In some data-scroll-sections I'me getting a 1px jitter somehow. Tried will-change: transform without success.

**Screenshots**
https://streamable.com/5iu52

**Desktop **
 - OS: macos
 - Browser Chrome
 - Version [80

Thank you 👊

**Comment by Djules** [comment]
It happens because of half-pixel computation by browser of the translate value applied to the sections.

I find out better results with value rounded to 2 decimals instead of 3. Even better if only one, or none, but I can't tell if the translation is as smooth as it should then.
May be someone in the team can check this out?

**Comment by tiansial** [comment]
Somehow, I didn't find the same issue in all of Locomotive sites. Wondering if it's some CSS on my project.

**Comment by quentinhocde** [comment]
Hey,

We always found a CSS solution, like @Djules says, It's a computation problem from the browser... I tried something, but I need to round the scroll value without decimals to not have this little line, and the translation isn't smoother.

Maybe the best solution is like every rendering browsers issues, adapt the Dom or play with the CSS 😕

Thanks ✌️

**Comment by P4KM4N** [comment]
@Djules how do you round up scroll.y value?
